[target.x86_64-unknown-linux-gnu ]
image = "lbeckman314/mdbook-latex:x86_64-unknown-linux-gnu"

# [target.i686-unknown-linux-gnu]
# image = "lbeckman314/mdbook-latex:i686-unknown-linux-gnu"

# [target.armv7-unknown-linux-gnueabihf
# image = "lbeckman314/mdbook-latex:armv7-unknown-linux-gnueabihf"
